package com.br.commonutils.view;

public enum FontType {

    ROBOTO_BLACK,
    ROBOTO_BLACK_ITALIC,
    ROBOTO_BOLD,
    ROBOTO_BOLD_ITALIC,
    ROBOTO_CONDENSED_BOLD,
    ROBOTO_CONDENSED_BOLD_ITALIC,
    ROBOTO_CONDENSED_ITALIC,
    ROBOTO_CONDENSED_LIGHT,
    ROBOTO_CONDENSED_LIGHT_ITALIC,
    ROBOTO_CONDENSED_REGULAR,
    ROBOTO_ITALIC,
    ROBOTO_LIGHT,
    ROBOTO_LIGHT_ITALIC,
    ROBOTO_MEDIUM,
    ROBOTO_MEDIUM_ITALIC,
    ROBOTO_REGULAR,
    ROBOTO_THIN,
    ROBOTO_THIN_ITALIC
}
